name: build

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'v18'
        registry-url: 'https://registry.npmjs.org'
    - name: Deploy Info
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Install
      run: bun install
    - name: Build
      run: bun run build
    - name: Test
      run: bun run test
    - name: Build Site
      run: bun build-site
    - name: Publish
      if: startsWith(github.ref, 'refs/tags/')
      run: bun publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - name: Publish Demo
      uses: JamesIves/github-pages-deploy-action@v4.3.0
      if: startsWith(github.ref, 'refs/tags/')
      with:
        branch: gh-pages
        folder: demo/out
        commit-message: Updates